version: '3'
services:
  app:
    build: app
    expose:
      - "8080"
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
